# Generated by Django 4.2.16 on 2024-10-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_type',
            field=models.CharField(choices=[('1099', '1099'), ('W2', 'W2')], default='W2', max_length=4),
        ),
        migrations.AddField(
            model_name='employee',
            name='social_security',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='travel_document',
            field=models.ImageField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
